### PR TITLE
Fix event import

### PR DESCRIPTION
**Pull request by GoldSucc**
Fixes https://github.com/cap-js/cds-typer/issues/382 (event import error).

### CODE REVIEW

**Comment by Janhouse** [comment]
Tested, seems to fix the issue.

**Comment by chgeo** [comment]
Can you provide more context on the issue?

**Comment by Janhouse** [comment]
@chgeo open the mentioned issue #382

**Comment by GoldSucc** [comment]
@chgeo when cds definition contains only events/operations it generates type without __ import which is incorrect ts file. tsc produces type errors indeed because no import is present. to get this error, event/operation should use type like Timestamp (something that comes from __. like __.CdsTimestamp).

**Comment by chgeo** [comment]
> @chgeo when cds definition (.cds file) contains only events/operations it generates type without __ import which is incorrect ts file. tsc produces type errors indeed because no import is present. to get this error, event/operation should use type like Timestamp (something that comes from __. like __.CdsTimestamp).

I see.  So I will add a test for that before merging.
Alternatively, you can give it a try.  See our [testing guide](https://github.com/cap-js/cds-typer/wiki/Testing) for this. Lately, we added [compilation tests](https://github.com/cap-js/cds-typer/wiki/Testing#writing-consumer-code) which are easier to write than the AST ones.

**Comment by GoldSucc** [comment]
@chgeo I have some experience with code generation and syntax trees so I decided to implement tests in AST. Committed changes with tests.

**Pull request merged**
